### PR TITLE
Update catalog and pc files with 1.2 version

### PR DESCRIPTION
**Pull request by dakk**
This pull updates references from 1.0 to 1.2, so we can use the correct  version in:

```python 
gi.require_version("OsmGpsMap", "1.2")
```

### CODE REVIEW

**Comment by johnny-bit** [comment]
seems like making it "1.2" causes CI problems...

**Comment by dakk** [comment]
@johnny-bit I see, no clue why

**Comment by dakk** [comment]
Update: now it compiles, but it fails on python test; I've updated the python test but the CI won't run since there is a conflict

**Comment by dreadnought** [comment]
Looking at your [fork](https://github.com/dakk/osm-gps-map) it I see this:
` This branch is 7 commits ahead, 41 commits behind nzjrs:master. `
It looks like you have to update your fork of this repository first, that should solve the merge conflict.
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by dakk** [comment]
@dreadnought my bad, a stupid error from me. I rebased with master and now all seems ok.

**Comment by johnny-bit** [comment]
OK, seems to be good overall :)

**Comment by johnny-bit** [comment]
Welp, this causes issues like darktable-org/darktable#10033 need to revert that...

**Pull request merged**
