### PR TITLE
Small fixes and optimizations from OSM2go

### PR DESCRIPTION
**Pull request by DerDakon**

### CODE REVIEW

**Comment by DerDakon** [comment]
ping?

**Comment by DerDakon** [comment]
Ping?

**Comment by phweyland** [comment]
@DerDakon you have moved max zoom to 19.
Is there any reason not to move to 20 ?
TIA

**Comment by johnny-bit** [comment]
@phweyland - In OSM wiki, zoom lvl 20 appeared several months after this PR was created (and merged). My assumption is that at the time of this PR it was simply not available. Let's test if it's available now...

**Comment by johnny-bit** [comment]
@phweyland - tested and it seems that OSM request with zoom=20 results in error 400 - bad request.

**Comment by phweyland** [comment]
> tested and it seems that OSM request with zoom=20 results in error 400 - bad request.

Do you see this at the console ? I see only  :
`OsmGpsMap-WARNING **: 14:51:58.888: Error getting missing tile`
which is common.

have you change osm_gps_map_source_get_max_zoom() accordingly ?

**Pull request merged**
